config/routes.rb
Minerva::Application.routes.draw do

  root :to=>"static_pages#admin"
  
  resources :users do
    collection do
      get :students_association
    end
  end
  
  resources :courses do
    collection do
      post :include_student
      post :remove_student
      get :show_students
    end
  end
  
  resources :logs
  
  devise_for :user
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

end

app/models/course.rb
class Course
  include Mongoid::Document
  
  field :title, :type => String, :default => ""
  has_and_belongs_to_many :users
  
end

app/models/log.rb
class Log
  include Mongoid::Document
  
  field :body, :type => String, :default => ""
end

app/models/user.rb
class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :role, :type => String, :default => ""
  field :first_name, :type => String, :default => ""
  
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :role

  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  field :remember_created_at, :type => Time

  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
    
  has_and_belongs_to_many :courses
  
  scope :all_students, where(:role=>"student")
  
end

app/controllers/application_controller.rb
require 'pp'
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(user)
    user_url(user)
  end
  
  def create_log(action_by, action, target)
    
    case action
    when "create_user"
      body = "#{action_by} criou o usuario #{target}"
    when "destroy_user"
      body = "#{action_by} excluiu o usuario #{target}"
    when "create_course"
      body = "#{action_by} criou o curso #{target}"
    when "destoy_course"
      body = "#{action_by} excluiu o curso #{target}"
    end
    
    Log.create(:body=>body)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
  def new
    @course = Course.new
  end
  
  def edit
    @course = Course.find(params[:id])
  end
  
  def create
    course = Course.create(params[:course])
    
    create_log(current_user.email, "create_course", course.title)
    redirect_to courses_path
  end
  
  def destroy
    course = Course.find(params[:id])
    course.destroy
    
    create_log(current_user.email, "destroy_course", course.title)
    redirect_to courses_path
  end
  
  def update
    course = Course.find(params[:id])
    course.update_attributes(params[:course])
    redirect_to courses_path
  end
  
  def include_student
    course = Course.find(params[:id])
    
    course.users << User.find(params[:user_id])
    course.save!
    
    redirect_to courses_path
  end
  
  def remove_student
    course = Course.find(params[:id])
    student = User.find(params[:user_id])
    
    course.users.delete(student)
    redirect_to courses_path
  end
  
  def show_students
    course = Course.find(params[:id])
    @students = course.users.all
    
    render :nothing=>true
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @logs = Log.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    user = User.new(params[:user])
    user.save

    create_log(current_user.email, "create_user", user.email)
    redirect_to users_path
  end
  
  def update
    user = User.find(params[:id])
    
    user.update_attributes(params[:user])

    redirect_to users_path
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    
    create_log(current_user.email, "destroy_user", user.email)
    redirect_to users_path
  end
  
  def students_association
    @students = User.all_students
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <p><%= f.text_field :title %></p>
  <%= f.submit "criar curso" %>
<% end %>

app/views/courses/edit.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="col-md-8">
    <%= link_to "criar um curso", new_course_path %>
    <%= render 'form' %>
  </div>
</div>

app/views/courses/index.html.erb
<%= render 'shared/header' %>  

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= render 'shared/admin_menu' %>
    </div>
    
    <div class="row col-md-8">
      <div class="menu">
        <%= link_to "criar um curso", new_course_path %>
      </div>
        <div class="courses">
          <% @courses.each do |course| %>
            <%= link_to course.title, course %> -
            <%= link_to 'excluir', course_path(course), method: :delete %> -
            <%= link_to 'editar', edit_course_path(course)%>
            <br>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="col-md-8">
    <%= link_to "criar um curso", new_course_path %>
    <%= render 'form' %>
  </div>
</div>

app/views/courses/show.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-8">
      <h4><%= @course.title %></h4>
      
      <div class="menu-course">
        <p><%= link_to "adicionar aluno para este curso", students_association_users_path %></p>
        <p><%= link_to "alunos deste curso", show_students_courses_path(@course.id) %></p>
      </div>
      
      
      <div class="students-info">
        <div class="title">Estudantes desse curso</div>
        <div class="students"></div>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minerva</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= alert %>
<%= yield %>

</body>
</html>

app/views/logs/index.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= render 'shared/admin_menu' %>
    </div>
    
    <div class="row col-md-8">
      <div class="users">
        <% @logs.each do |log| %>
          <p><%= log.body %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_admin_menu.html.erb
<div class="menu">
  <p><%= link_to 'gerenciar cursos', courses_path %></p>
  <p><%= link_to 'gerenciar usuarios', users_path %></p>
  <p><%= link_to 'histórico', logs_path %></p>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

<br><br><br><br>

app/views/static_pages/admin.html.erb
<%= render 'shared/header' %>  

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= render 'shared/admin_menu' %>
    </div>
  
    <div class="col-md-8">
      londerson
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <p><b>Nome:</b></p>
  <p><%= f.text_field :first_name %></p>
  
  <p><b>Email:</b></p>
  <p><%= f.text_field :email %></p>
  
  <%= f.select :role, options_for_select([["Professor", "teacher"], ["Estudante", "student"], ["Administrador", "administrator"]]) %>
  
  <p><b>Senha:</b></p>
  <p><%= f.text_field :password, :type=>"password" %></p>
  
  <p><%= f.submit %></p>
  
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/header' %>  

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= render 'shared/admin_menu' %>
    </div>
    
    <div class="row col-md-8">
      <div class="menu">
        <%= link_to "criar um usuário", new_user_path %>
      </div>
        <div class="users">
          <% @users.each do |user| %>
            <%= link_to user.first_name, user %> |
            <%= user.role %> |
            <%= link_to 'excluir', user_path(user), method: :delete %> |
            <%= link_to 'editar', edit_user_path(user)%>
            <br>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/header' %>
<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>

  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="col-md-8">
    <%= @user.first_name %>
  </div>
</div>

app/views/users/students_association.html.erb
<%= render 'shared/header' %>  

<div class="container">

  <div class="row col-md-3 sidebar-offcanvas">
    <div class="menu">
      <%= render 'shared/admin_menu' %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-8">
      <h3>Alunos</h3>
      <% @students.each do |student| %>
        <p><%= student.first_name %></p>
      <% end %>
    </div>
  </div>
  
</div>